### ISSUE TITLE
Occasional test error during `mvn package`

### ISSUE THREAD

**Issue by rfelcman** [dalexandrov/task#1]
There is occasional test error during `mvn package`
see
```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.005 s <<< FAILURE! - in local.mitia.combiner.TestNormalRun
[ERROR] local.mitia.combiner.TestNormalRun.testMultipleServers  Time elapsed: 4.026 s  <<< FAILURE!
		java.lang.AssertionError: expected:<157> but was:<156>
			at local.mitia.combiner.TestNormalRun.checkUniqueOutput(TestNormalRun.java:134)
			at local.mitia.combiner.TestNormalRun.testMultipleServers(TestNormalRun.java:71)
```

**Comment by dalexandrov** [comment]
Probably the 3 machines and the connections between them, I've used for testing are quite fast. Will tune the waiting time.

**Comment by dalexandrov** [comment]
Please review https://github.com/dalexandrov/task/commit/54e1bd36c3be06d75d9001818a24074d183d839c
